version: '3.8'

services:
  discovery:
    build:
      context: .  # Path to the directory containing the Dockerfile for service discovery
    container_name: discovery
    ports:
      - "8761:8761"
    networks:
      - revshop_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s  # Check every 30 seconds
      timeout: 10s   # Timeout after 10 seconds
      retries: 3     # Mark as unhealthy after 3 failures

  config-server:
    build:
      context: ../ConfigServerRevshop  # Path to the Config Server Dockerfile
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - revshop_network
    environment:
      - SPRING_PROFILES_ACTIVE=native
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  buyermicroservice:
    build:
      context: ../BuyerMicroService  # Path to the BuyerMicroservice Dockerfile
    container_name: buyermicroservice_container
    depends_on:
      config-server:
        condition: service_healthy  # Wait for Config Server to be healthy
      discovery:
        condition: service_healthy  # Wait for Discovery to be healthy
    ports:
      - "8000:8000"
    networks:
      - revshop_network
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://buyerdb:3306/buyer
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_CLOUD_CONFIG_FAIL_FAST=false

  api-gateway:
    build:
      context: ../APIGatewayRevshop  # Path to the API Gateway Dockerfile
    container_name: apigatewayrevshop_container
    ports:
      - "8080:8080"
    depends_on:
      config-server:
        condition: service_healthy
      discovery:
        condition: service_healthy
    networks:
      - revshop_network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888
      - SPRING_CLOUD_CONFIG_FAIL_FAST=false

  buyerdb:
    image: mysql:latest
    container_name: buyerdb
    ports:
      - "3304:3306"
    networks:
      - revshop_network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: buyer
    volumes:
      - buyerdb_volume:/var/lib/mysql

networks:
  revshop_network:

volumes:
  buyerdb_volume:
